http:
  addr: "127.0.0.1:8080"

shutdown_timeout: "10s"
chunks_count: 5

storage:
  num_of_storages: 5
  type: "InMemory"

db:
  user: meta
  name: meta
  password: meta
  host: 127.0.0.1
  port: 5432

balancer:
  hosts:
    - host1
    - host2
    - host3
    - host4
    - host5
    - host6
    - host7
    - host8
    - host9
    - host10
